services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: financeiro-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Rafael.2026!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - financeiro-net
    volumes:
      - sqlserver_data:/var/opt/mssql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: financeiro-auth
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
    ports:
      - "8080:8080"
    networks:
      - financeiro-net

  redis:
    image: redis:alpine
    container_name: financeiro-cache
    ports:
      - "6379:6379"
    networks:
      - financeiro-net

  api:
    build:
      context: .
      dockerfile: Financeiro.Api/Dockerfile
    container_name: financeiro-api
    ports:
      - "5283:5283"
    depends_on:
      - sqlserver
      - redis
      - keycloak
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=financeiro;User Id=sa;Password=Rafael.2026!;TrustServerCertificate=True;
      - ConnectionStrings__Redis=redis:6379
      - Keycloak__BaseUrl=http://keycloak:8080
      - Keycloak__ClientId=financeiro-api
    networks:
      - financeiro-net

  web:
    build:
      context: ./Financeiro.Web
      dockerfile: Dockerfile
    container_name: financeiro-web
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - financeiro-net

networks:
  financeiro-net:
    driver: bridge

volumes:
  sqlserver_data:
