services:
  postgres:
    image: postgres:16
    container_name: financeiro-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Rafael.2026!
      - POSTGRES_DB=financeiro
    ports:
      - "5432:5432"
    networks:
      - financeiro-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: financeiro-auth
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
    ports:
      - "8080:8080"
    networks:
      - financeiro-net

  redis:
    image: redis:alpine
    container_name: financeiro-cache
    ports:
      - "6379:6379"
    networks:
      - financeiro-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: financeiro-logs
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - financeiro-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: financeiro-dashboard
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - financeiro-net

networks:
  financeiro-net:
    driver: bridge

volumes:
  postgres_data:
